### ISSUE TITLE
Proxy Manager always exit

### ISSUE THREAD

**Issue by leepood** [luminati-io/luminati-proxy#103]
Hi, Bro
 I have always encountered the problem of proxy manager  exit recently. Please check the log as follows

```
2018-06-12 08:33:34.011 NOTICE: 22999 Starting proxies 24009:5009
2018-06-12 08:33:34.227 NOTICE: 24009 Refreshing all sessions
2018-06-12 08:33:35.424 NOTICE: 24009 Refreshing all sessions
2018-06-12 08:33:50.478 CRIT: 22999 uncaughtException, error = TypeError: Cannot read property 'once' of undefined
    at Socks.proxy_http (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/lib/socks.js:88:12)
    at Socks.handler (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/lib/socks.js:32:21)
    at Server.emit (events.js:160:13)
    at Parser.<anonymous> (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/node_modules/@luminati-io/socksv5/lib/server.js:130:12)
    at Parser.emit (events.js:160:13)
    at Parser._onData (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/node_modules/@luminati-io/socksv5/lib/server.parser.js:209:16)
    at Socket.Parser.__onData (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/node_modules/@luminati-io/socksv5/lib/server.parser.js:23:10)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:599:20)
2018-06-12 08:33:50.521 ERR: 22999 uncaughtException, error = TypeError: Cannot read property 'once' of undefined
    at Socks.proxy_http (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/lib/socks.js:88:12)
    at Socks.handler (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/lib/socks.js:32:21)
    at Server.emit (events.js:160:13)
    at Parser.<anonymous> (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/node_modules/@luminati-io/socksv5/lib/server.js:130:12)
    at Parser.emit (events.js:160:13)
    at Parser._onData (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/node_modules/@luminati-io/socksv5/lib/server.parser.js:209:16)
    at Socket.Parser.__onData (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/node_modules/@luminati-io/socksv5/lib/server.parser.js:23:10)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:599:20) TypeError: Cannot read property 'once' of undefined
2018-06-12 08:33:51.434 NOTICE: 22999 Manager stopped {"reason":"uncaughtException, error = TypeError: Cannot read property 'once' of undefined\n    at Socks.proxy_http (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/lib/socks.js:88:12)\n    at Socks.handler (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/lib/socks.js:32:21)\n    at Server.emit (events.js:160:13)\n    at Parser.<anonymous> (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/node_modules/@luminati-io/socksv5/lib/server.js:130:12)\n    at Parser.emit (events.js:160:13)\n    at Parser._onData (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/node_modules/@luminati-io/socksv5/lib/server.parser.js:209:16)\n    at Socket.Parser.__onData (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/node_modules/@luminati-io/socksv5/lib/server.parser.js:23:10)\n    at Socket.emit (events.js:160:13)\n    at addChunk (_stream_readable.js:269:12)\n    at readableAddChunk (_stream_readable.js:256:11)\n    at Socket.Readable.push (_stream_readable.js:213:10)\n    at TCP.onread (net.js:599:20)","force":true}
2018-06-12 08:33:51.435 NOTICE: 22999 Stopping proxies 22225
2018-06-12 08:33:51.439 NOTICE: 22999 Stopping proxies 24003
2018-06-12 08:33:51.439 NOTICE: 22999 Stopping proxies 24004

```

**Comment by fudali** [comment]
Hi. Do you use SOCKS protocol? We rebuilt the way SOCKS works and the new version is being released very soon

**Comment by hotkingda** [comment]
I'm looking forward to your socks

**Comment by leepood** [comment]
@fudali hi, Yes, we use socks protocol. I have added the null pointer check to the `socks.js` file  at line 88 and function `Socks.prototype.bypass ` .  Now, it's much more better than before. But sometimes , some other errors caused the process to exit . So i'm looking forward for your new released version!

**Comment by fudali** [comment]
Hi @leepood,
We released a new version with improved SOCKS supports. It uses the same port for SOCKS and HTTP/HTTPS connections. Please upgrade and close an issue if it's resolved. If you have any other issues, please open a separate issue

Krzysztof from Luminati

**Comment by leepood** [comment]
hi @fudali , I will checked it as soon as possible.
