### ISSUE TITLE
ParserIncomingMessage is not a constructor

### ISSUE THREAD

**Issue by JannikZed** [luminati-io/luminati-proxy#110]
When trying to add an external proxy like this: `['gw-1.XXX.de:8080']` the proxy manager fails completely with following log message:

```
2018-07-16 10:39:23.914 CRIT: uncaughtException, error = TypeError: ParserIncomingMessage is not a constructor
16.7.2018 12:39:24     at HTTPParser.parserOnHeadersComplete (_http_common.js:81:21)
16.7.2018 12:39:24     at socketOnData (_http_server.js:472:20)
16.7.2018 12:39:24     at Socket.emit (events.js:180:13)
16.7.2018 12:39:24     at Socket.Readable.read (_stream_readable.js:487:10)
16.7.2018 12:39:24     at flow (_stream_readable.js:858:34)
16.7.2018 12:39:24     at resume_ (_stream_readable.js:840:3)
16.7.2018 12:39:24     at process._tickCallback (internal/process/next_tick.js:178:19)
16.7.2018 12:39:24 2018-07-16 10:39:24.010 ERR: Shutdown, reason is uncaughtException, error = TypeError: ParserIncomingMessage is not a constructor
16.7.2018 12:39:24     at HTTPParser.parserOnHeadersComplete (_http_common.js:81:21)
16.7.2018 12:39:24     at socketOnData (_http_server.js:472:20)
16.7.2018 12:39:24     at Socket.emit (events.js:180:13)
16.7.2018 12:39:24     at Socket.Readable.read (_stream_readable.js:487:10)
16.7.2018 12:39:24     at flow (_stream_readable.js:858:34)
16.7.2018 12:39:24     at resume_ (_stream_readable.js:840:3)
16.7.2018 12:39:24     at process._tickCallback (internal/process/next_tick.js:178:19): TypeError: ParserIncomingMessage is not a constructor
16.7.2018 12:39:24     at HTTPParser.parserOnHeadersComplete (_http_common.js:81:21)
16.7.2018 12:39:24     at socketOnData (_http_server.js:472:20)
16.7.2018 12:39:24     at Socket.emit (events.js:180:13)
16.7.2018 12:39:24     at Socket.Readable.read (_stream_readable.js:487:10)
16.7.2018 12:39:24     at flow (_stream_readable.js:858:34)
16.7.2018 12:39:24     at resume_ (_stream_readable.js:840:3)
16.7.2018 12:39:24     at process._tickCallback (internal/process/next_tick.js:178:19)
16.7.2018 12:39:24 2018-07-16 10:39:24.455 NOTICE: 22999 Manager stopped {"reason":"uncaughtException, error = TypeError: ParserIncomingMessage is not a constructor\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:81:21)\n    at socketOnData (_http_server.js:472:20)\n    at Socket.emit (events.js:180:13)\n    at Socket.Readable.read (_stream_readable.js:487:10)\n    at flow (_stream_readable.js:858:34)\n    at resume_ (_stream_readable.js:840:3)\n    at process._tickCallback (internal/process/next_tick.js:178:19)","force":true}
```

Any idea why?

**Comment by assafza** [comment]
Hi,

This looks like a node version issue.
Please contact Luminati support @ [](http://luminati.io/cp)  you still cant overcome this issue.

Assaf
