### ISSUE TITLE
proxy manager aways exit!

### ISSUE THREAD

**Issue by wjdimba** [luminati-io/luminati-proxy#113]
uncaughtException, error = TypeError: Cannot read property 'emit' of undefined
    at Socket.socket.once.data (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/lib/luminati.js:1109:35)
 at Object.onceWrapper (events.js:255:19)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:599:20)
2018-08-13 06:35:56.354 ERR: Shutdown, reason is uncaughtException, error = TypeError: Cannot read property 'emit' of undefined
    at Socket.socket.once.data (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/lib/luminati.js:1109:35)
    at Object.onceWrapper (events.js:255:19)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:599:20): TypeError: Cannot read property 'emit' of undefined
    at Socket.socket.once.data (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/lib/luminati.js:1109:35)
    at Object.onceWrapper (events.js:255:19)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:599:20)

**Comment by assafza** [comment]
Hi @wjdimba please update to the latest version and if the issue persists contact us.
