### ISSUE TITLE
Can't start lpm after upgrade

### ISSUE THREAD

**Issue by splebel** [luminati-io/luminati-proxy#116]
After upgrading from 1.90.563 to the latest 1.106.970 I'm not able to start the service.

The upgrade was done using npm.

Here's the log:
```
Sep  6 15:16:38 proxy01 luminati_proxy[28105]: Tag: 1.106.970
Sep  6 15:16:38 proxy01 luminati_proxy[28105]: Build date: 06-Sep-18 10:30:33
Sep  6 15:16:38 proxy01 luminati_proxy[28105]: Make flags: DIST=APP RELEASE=y CC64_32=y CONFIG_LUM_LOCAL=y CONFIG_B
ATREQ=y CONFIG_BAT_CYCLE=y CONFIG_BAT_PLATFORM=app_win32r
Sep  6 15:16:38 proxy01 luminati_proxy[28105]: Os version: linux x64 4.13.0-1011-gcp
Sep  6 15:16:38 proxy01 luminati_proxy[28105]: Host name: proxy01
Sep  6 15:16:38 proxy01 luminati_proxy[28105]: 2018-09-06 15:16:38.239 NOTICE: 22999 Manager started 1.106.970
Sep  6 15:16:38 proxy01 luminati_proxy[28105]: Loaded config /opt/luminati/luminati.json
Sep  6 15:16:38 proxy01 luminati_proxy[28105]: Running proxy configurations...
Sep  6 15:16:38 proxy01 luminati_proxy[28105]: 2018-09-06 15:16:38.461 NOTICE: 22999 Starting proxies 24001
Sep  6 15:16:38 proxy01 luminati_proxy[28105]: 2018-09-06 15:16:38.465 NOTICE: 22999 Starting proxies 24002
Sep  6 15:16:38 proxy01 luminati_proxy[28105]: 2018-09-06 15:16:38.466 NOTICE: 22999 Starting proxies 24003
Sep  6 15:16:38 proxy01 luminati_proxy[28105]: 2018-09-06 15:16:38.467 NOTICE: 22999 Starting proxies 24004
Sep  6 15:16:38 proxy01 luminati_proxy[28105]: 2018-09-06 15:16:38.468 NOTICE: 22999 Starting proxies 24005
Sep  6 15:16:38 proxy01 luminati_proxy[28105]: 2018-09-06 15:16:38.469 NOTICE: 22999 Starting proxies 24006
Sep  6 15:16:38 proxy01 luminati_proxy[28105]: 2018-09-06 15:16:38.469 NOTICE: 22999 Starting proxies 24007
Sep  6 15:16:38 proxy01 luminati_proxy[28105]: 2018-09-06 15:16:38.470 NOTICE: 22999 Starting proxies 24008
Sep  6 15:16:38 proxy01 luminati_proxy[28105]: 2018-09-06 15:16:38.471 NOTICE: 22999 Starting proxies 24009
Sep  6 15:16:38 proxy01 luminati_proxy[28105]: 2018-09-06 15:16:38.472 NOTICE: 22999 Starting proxies 24010
Sep  6 15:16:38 proxy01 luminati_proxy[28105]: 2018-09-06 15:16:38.474 NOTICE: 22999 Starting proxies 24000
Sep  6 15:16:38 proxy01 luminati_proxy[28105]: 2018-09-06 15:16:38.475 NOTICE: 22999 Starting proxies 22225
Sep  6 15:16:41 proxy01 luminati_proxy[28105]: ==================================================
Sep  6 15:16:41 proxy01 luminati_proxy[28105]: =                                                =
Sep  6 15:16:41 proxy01 luminati_proxy[28105]: =      Local proxy manager client is running     =
Sep  6 15:16:41 proxy01 luminati_proxy[28105]: =                                                =
Sep  6 15:16:41 proxy01 luminati_proxy[28105]: =               Open admin browser:              =
Sep  6 15:16:41 proxy01 luminati_proxy[28105]: =                                                =
Sep  6 15:16:41 proxy01 luminati_proxy[28105]: =             http://127.0.0.1:22999             =
Sep  6 15:16:41 proxy01 luminati_proxy[28105]: =                                                =
Sep  6 15:16:41 proxy01 luminati_proxy[28105]: =                                                =
Sep  6 15:16:41 proxy01 luminati_proxy[28105]: =    Do not close the process while using the    =
Sep  6 15:16:41 proxy01 luminati_proxy[28105]: =    Proxy Manager                               =
Sep  6 15:16:41 proxy01 luminati_proxy[28105]: =                                                =
Sep  6 15:16:41 proxy01 luminati_proxy[28105]: ==================================================
Sep  6 15:16:56 proxy01 luminati_proxy[28105]: 2018-09-06 15:16:56.903 NOTICE: 22999 Manager stopped {"reason":"unc
aughtException, error = TypeError: ParserIncomingMessage is not a constructor\n    at HTTPParser.parserOnHeadersCom
plete (_http_common.js:81:21)\n    at socketOnData (_http_server.js:472:20)\n    at Socket.emit (events.js:180:13)\
n    at Socket.Readable.read (_stream_readable.js:487:10)\n    at flow (_stream_readable.js:858:34)\n    at resume_
 (_stream_readable.js:840:3)\n    at process._tickCallback (internal/process/next_tick.js:178:19)","force":true}
Sep  6 15:16:56 proxy01 luminati_proxy[28105]: 2018-09-06 15:16:56.904 NOTICE: 22999 Stopping proxies 22225
Sep  6 15:16:56 proxy01 luminati_proxy[28105]: 2018-09-06 15:16:56.904 NOTICE: 22999 Stopping proxies 24000
Sep  6 15:16:56 proxy01 luminati_proxy[28105]: 2018-09-06 15:16:56.905 NOTICE: 22999 Stopping proxies 24001,24002,2
4003,24004,24005,24006,24007,24008,24009,24010
Sep  6 15:16:56 proxy01 luminati_proxy[28105]: 2018-09-06 15:16:56.809 CRIT: uncaughtException, error = TypeError: ParserIncomingMessage is not a constructor
Sep  6 15:16:56 proxy01 luminati_proxy[28105]:     at HTTPParser.parserOnHeadersComplete (_http_common.js:81:21)
Sep  6 15:16:56 proxy01 luminati_proxy[28105]:     at socketOnData (_http_server.js:472:20)
Sep  6 15:16:56 proxy01 luminati_proxy[28105]:     at Socket.emit (events.js:180:13)
Sep  6 15:16:56 proxy01 luminati_proxy[28105]:     at Socket.Readable.read (_stream_readable.js:487:10)
Sep  6 15:16:56 proxy01 luminati_proxy[28105]:     at flow (_stream_readable.js:858:34)
Sep  6 15:16:56 proxy01 luminati_proxy[28105]:     at resume_ (_stream_readable.js:840:3)
Sep  6 15:16:56 proxy01 luminati_proxy[28105]:     at process._tickCallback (internal/process/next_tick.js:178:19)
Sep  6 15:16:56 proxy01 luminati_proxy[28105]: 2018-09-06 15:16:56.813 ERR: Shutdown, reason is uncaughtException, error = TypeError: ParserIncomingMessage is not a constructor
Sep  6 15:16:56 proxy01 luminati_proxy[28105]:     at HTTPParser.parserOnHeadersComplete (_http_common.js:81:21)
Sep  6 15:16:56 proxy01 luminati_proxy[28105]:     at socketOnData (_http_server.js:472:20)
Sep  6 15:16:56 proxy01 luminati_proxy[28105]:     at Socket.emit (events.js:180:13)
Sep  6 15:16:56 proxy01 luminati_proxy[28105]:     at Socket.Readable.read (_stream_readable.js:487:10)
Sep  6 15:16:56 proxy01 luminati_proxy[28105]:     at flow (_stream_readable.js:858:34)
Sep  6 15:16:56 proxy01 luminati_proxy[28105]:     at resume_ (_stream_readable.js:840:3)
Sep  6 15:16:56 proxy01 luminati_proxy[28105]:     at process._tickCallback (internal/process/next_tick.js:178:19): TypeError: ParserIncomingMessage is not a constructor
Sep  6 15:16:56 proxy01 luminati_proxy[28105]:     at HTTPParser.parserOnHeadersComplete (_http_common.js:81:21)
Sep  6 15:16:56 proxy01 luminati_proxy[28105]:     at socketOnData (_http_server.js:472:20)
Sep  6 15:16:56 proxy01 luminati_proxy[28105]:     at Socket.emit (events.js:180:13)
Sep  6 15:16:56 proxy01 luminati_proxy[28105]:     at Socket.Readable.read (_stream_readable.js:487:10)
Sep  6 15:16:56 proxy01 luminati_proxy[28105]:     at flow (_stream_readable.js:858:34)
Sep  6 15:16:56 proxy01 luminati_proxy[28105]:     at resume_ (_stream_readable.js:840:3)
Sep  6 15:16:56 proxy01 luminati_proxy[28105]:     at process._tickCallback (internal/process/next_tick.js:178:19)
Sep  6 15:16:56 proxy01 luminati_proxy[28105]: 2018-09-06 15:16:56.816 CRIT: uncaughtException, error = TypeError: ParserIncomingMessage is not a constructor
Sep  6 15:16:56 proxy01 luminati_proxy[28105]:     at HTTPParser.parserOnHeadersComplete (_http_common.js:81:21)
Sep  6 15:16:56 proxy01 luminati_proxy[28105]:     at socketOnData (_http_server.js:472:20)
Sep  6 15:16:56 proxy01 luminati_proxy[28105]:     at Socket.emit (events.js:180:13)
Sep  6 15:16:56 proxy01 luminati_proxy[28105]:     at Socket.Readable.read (_stream_readable.js:487:10)
Sep  6 15:16:56 proxy01 luminati_proxy[28105]:     at flow (_stream_readable.js:858:34)
Sep  6 15:16:56 proxy01 luminati_proxy[28105]:     at resume_ (_stream_readable.js:840:3)
Sep  6 15:16:56 proxy01 luminati_proxy[28105]:     at process._tickCallback (internal/process/next_tick.js:178:19)
```

Anything I should look after?

**Comment by assafza** [comment]
Hi @splebel please contact your account manager to help you with this. we have 24x7 support for those cases.
