### ISSUE TITLE
Crashed while editing.

### ISSUE THREAD

**Issue by residualmind** [luminati-io/luminati-proxy#121]
version: v1.107.802
This already happened a few releases earlier:

While editing rules and 'general' settings in LPM, sometimes the application crashes.

logs:
```
2018-09-19 10:20:59.560 ERR: 24000 send proxy ssl error Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at Socket.socketCloseListener (_http_client.js:362:23)
    at Socket.emit (events.js:165:20)
    at TCP._handle.close [as _onclose] (net.js:559:12)
2018-09-19 10:20:59.561 ERR: 24000 send proxy ssl error Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at Socket.socketCloseListener (_http_client.js:362:23)
    at Socket.emit (events.js:165:20)
    at TCP._handle.close [as _onclose] (net.js:559:12)
2018-09-19 10:20:59.562 ERR: 24000 send proxy ssl error Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at Socket.socketCloseListener (_http_client.js:362:23)
    at Socket.emit (events.js:165:20)
    at TCP._handle.close [as _onclose] (net.js:559:12)
2018-09-19 10:20:59.562 ERR: 24000 send proxy ssl error Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at Socket.socketCloseListener (_http_client.js:362:23)
    at Socket.emit (events.js:165:20)
    at TCP._handle.close [as _onclose] (net.js:559:12)
2018-09-19 10:20:59.563 ERR: 24000 send proxy ssl error Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at Socket.socketCloseListener (_http_client.js:362:23)
    at Socket.emit (events.js:165:20)
    at TCP._handle.close [as _onclose] (net.js:559:12)
2018-09-19 10:20:59.563 ERR: 24000 send proxy ssl error Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at Socket.socketCloseListener (_http_client.js:362:23)
    at Socket.emit (events.js:165:20)
    at TCP._handle.close [as _onclose] (net.js:559:12)
2018-09-19 10:20:59.564 ERR: 24000 send proxy ssl error Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at Socket.socketCloseListener (_http_client.js:362:23)
    at Socket.emit (events.js:165:20)
    at TCP._handle.close [as _onclose] (net.js:559:12)
2018-09-19 10:20:59.564 ERR: 24000 send proxy ssl error Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at Socket.socketCloseListener (_http_client.js:362:23)
    at Socket.emit (events.js:165:20)
    at TCP._handle.close [as _onclose] (net.js:559:12)
2018-09-19 10:20:59.565 ERR: 24000 send proxy ssl error Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at Socket.socketCloseListener (_http_client.js:362:23)
    at Socket.emit (events.js:165:20)
    at TCP._handle.close [as _onclose] (net.js:559:12)
2018-09-19 10:21:09.572 NOTICE: 22999 Stopping proxies 24001
2018-09-19 10:21:09.579 NOTICE: 22999 Starting proxies 24001
2018-09-19 10:21:09.591 ERR: 24000 send proxy ssl error Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at Socket.socketCloseListener (_http_client.js:362:23)
    at Socket.emit (events.js:165:20)
    at TCP._handle.close [as _onclose] (net.js:559:12)
2018-09-19 10:21:09.592 ERR: 24000 send proxy ssl error Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at Socket.socketCloseListener (_http_client.js:362:23)
    at Socket.emit (events.js:165:20)
    at TCP._handle.close [as _onclose] (net.js:559:12)
2018-09-19 10:21:09.593 ERR: 24000 send proxy ssl error Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at Socket.socketCloseListener (_http_client.js:362:23)
    at Socket.emit (events.js:165:20)
    at TCP._handle.close [as _onclose] (net.js:559:12)
2018-09-19 10:21:19.511 NOTICE: 22999 Stopping proxies 24000
2018-09-19 10:21:19.524 WARN: 24000 Closing TCP: Cannot read property '_isIdle' of undefined
2018-09-19 10:21:19.535 NOTICE: 22999 Starting proxies 24000
2018-09-19 10:21:20.404 NOTICE: 22999 Manager stopped {"reason":"uncaughtException, error = TypeError: Cannot read property 'writeQueueSize' of null\n    at TLSSocket.Socket._writeGeneric (net.js:769:33)\n    at TLSSocket.Socket._writev (net.js:777:8)\n    at doWrite (_stream_writable.js:405:12)\n    at clearBuffer (_stream_writable.js:511:5)\n    at TLSSocket.Writable.uncork (_stream_writable.js:313:7)\n    at connectionCorkNT (_http_outgoing.js:692:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","force":true}
2018-09-19 10:21:20.406 NOTICE: 22999 Stopping proxies 24000
2018-09-19 10:21:20.407 NOTICE: 22999 Stopping proxies 24001
2018-09-19 10:21:20.407 NOTICE: 22999 Stopping proxies 24002
2018-09-19 10:21:20.408 NOTICE: 22999 Stopping proxies 24003
2018-09-19 10:21:20.408 NOTICE: 22999 Stopping proxies 24004
2018-09-19 10:21:19.548 CRIT: uncaughtException, error = TypeError: Cannot read property 'writeQueueSize' of null
    at TLSSocket.Socket._writeGeneric (net.js:769:33)
    at TLSSocket.Socket._writev (net.js:777:8)
    at doWrite (_stream_writable.js:405:12)
    at clearBuffer (_stream_writable.js:511:5)
    at TLSSocket.Writable.uncork (_stream_writable.js:313:7)
    at connectionCorkNT (_http_outgoing.js:692:8)
    at process._tickCallback (internal/process/next_tick.js:152:19)
2018-09-19 10:21:19.604 ERR: Shutdown, reason is uncaughtException, error = TypeError: Cannot read property 'writeQueueSize' of null
    at TLSSocket.Socket._writeGeneric (net.js:769:33)
    at TLSSocket.Socket._writev (net.js:777:8)
    at doWrite (_stream_writable.js:405:12)
    at clearBuffer (_stream_writable.js:511:5)
    at TLSSocket.Writable.uncork (_stream_writable.js:313:7)
    at connectionCorkNT (_http_outgoing.js:692:8)
    at process._tickCallback (internal/process/next_tick.js:152:19): TypeError: Cannot read property 'writeQueueSize' of null
    at TLSSocket.Socket._writeGeneric (net.js:769:33)
    at TLSSocket.Socket._writev (net.js:777:8)
    at doWrite (_stream_writable.js:405:12)
    at clearBuffer (_stream_writable.js:511:5)
    at TLSSocket.Writable.uncork (_stream_writable.js:313:7)
    at connectionCorkNT (_http_outgoing.js:692:8)
    at process._tickCallback (internal/process/next_tick.js:152:19)

```

**Comment by fudali** [comment]
What node version are you using? Can you try if this also crashes with node 8.11.X?

**Comment by residualmind** [comment]
Hi, I'm always using the node version that comes with the provided docker image.
Haven't seen the problem with newer versions, yet.

**Comment by fudali** [comment]
Ok so seems to be fixed. If happens again, please reopen
