### ISSUE TITLE
lpm crashes every few minutes with this error 

### ISSUE THREAD

**Issue by residualmind** [luminati-io/luminati-proxy#123]
```
2018-09-21 15:55:08.741 CRIT: uncaughtException, error = TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["set-cookie"]
    at storeHeader (_http_outgoing.js:445:13)
    at ServerResponse._storeHeader (_http_outgoing.js:346:13)
    at ServerResponse.writeHead (_http_server.js:256:8)
    at write_http_reply (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/lib/luminati.js:68:24)
    at IncomingMessage._res.on (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/lib/luminati.js:1128:25)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
2018-09-21 15:55:08.745 ERR: Shutdown, reason is uncaughtException, error = TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["set-cookie"]
    at storeHeader (_http_outgoing.js:445:13)
    at ServerResponse._storeHeader (_http_outgoing.js:346:13)
    at ServerResponse.writeHead (_http_server.js:256:8)
    at write_http_reply (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/lib/luminati.js:68:24)
    at IncomingMessage._res.on (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/lib/luminati.js:1128:25)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19): TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["set-cookie"]
    at storeHeader (_http_outgoing.js:445:13)
    at ServerResponse._storeHeader (_http_outgoing.js:346:13)
    at ServerResponse.writeHead (_http_server.js:256:8)
    at write_http_reply (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/lib/luminati.js:68:24)
    at IncomingMessage._res.on (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/lib/luminati.js:1128:25)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)
2018-09-21 15:55:09.274 NOTICE: 22999 Manager stopped {"reason":"uncaughtException, error = TypeError [ERR_INVALID_CHAR]: Invalid character in header content [\"set-cookie\"]\n    at storeHeader (_http_outgoing.js:445:13)\n    at ServerResponse._storeHeader (_http_outgoing.js:346:13)\n    at ServerResponse.writeHead (_http_server.js:256:8)\n    at write_http_reply (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/lib/luminati.js:68:24)\n    at IncomingMessage._res.on (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/lib/luminati.js:1128:25)\n    at IncomingMessage.emit (events.js:165:20)\n    at endReadableNT (_stream_readable.js:1101:12)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","force":true}
2018-09-21 15:55:09.276 NOTICE: 22999 Stopping proxies 24000
2018-09-21 15:55:09.284 WARN: 24000 Closing TCP: Cannot read property '_isIdle' of undefined
2018-09-21 15:55:09.287 NOTICE: 22999 Stopping proxies 24001
2018-09-21 15:55:09.287 NOTICE: 22999 Stopping proxies 24002
2018-09-21 15:55:09.287 NOTICE: 22999 Stopping proxies 24003
2018-09-21 15:55:09.288 NOTICE: 22999 Stopping proxies 24004

```

**Comment by assafza** [comment]
Hi @residualmind does this happens on a specific action? which version are you using?
@fudali

**Comment by fudali** [comment]
Hi @residualmind ,

> Invalid character in header content ["set-cookie"]

Can you provide us with what kind of request you send when it crashes with that error? Are you able to check what is the value of 'set-cookie' header?

**Comment by residualmind** [comment]
Hi, I can say that it only seems to happen when "SSL logs" is enabled. What kind of request causes this is harder to determine since LPM crashes that moment and I don't get proper logs on our side without adding extra debugging statements on our production system.

Currently using the docker image v1.107.868 provided by you. (https://hub.docker.com/r/luminati/luminati-proxy)

**Comment by fudali** [comment]
It's fixed already. Please upgrade your LPM
