### ISSUE TITLE
The luminati-proxy always exit. TypeError: Cannot read property 'stats' of undefined

### ISSUE THREAD

**Issue by yangyangFE** [luminati-io/luminati-proxy#138]
Hi.
the error stack is: 

uncaughtException, error = TypeError: Cannot read property 'stats' of undefined
    at Manager.regenerate_stats.stat [as regenerate_stats] (/usr/lib/node_modules/@luminati-io/luminati-proxy/lib/manager.js:278:47)
    at Immediate.setImmediate (/usr/lib/node_modules/@luminati-io/luminati-proxy/lib/manager.js:303:35)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
2018-11-02 09:26:44.654 NOTICE: 22999 Stopping proxies 24000
2018-11-02 09:26:44.656 NOTICE: 22999 Stopping proxies 24001

**Comment by fudali** [comment]
Hi, thanks for reporting! This has been already resolved. Please upgrade LPM. If you still encounter issues feel free to reopen
