### ISSUE TITLE
LPM meet ECONNRESET error and crash

### ISSUE THREAD

**Issue by khtq** [luminati-io/luminati-proxy#180]
The bellow error occurred and LPM crash:

> 2019-04-02 16:29:00.556 ERR: 22999 uncaught exception Error: read ECONNRESET 
> 	at TCP.onStreamRead (internal/stream_base_commons.js:111:27)

Configuration file:
```
{
  "_defaults": {
    "customer": "",
    "password": "",
    "token": "",
    "version": "1.128.768"
  },
  "proxies": [
    {
      "keep_alive": true,
      "last_preset_applied": "custom",
      "max_requests": 0,
      "password": "",
      "pool_type": "long_availability",
      "port": 24000,
      "proxy": "servercountry-us.zproxy.lum-superproxy.io",
      "rules": [
        {
          "action": {
            "bypass_proxy": true
          },
          "action_type": "bypass_proxy",
          "trigger_code": "function trigger(opt){\n  if (!/xxx.com/.test(opt.url))\n    return true;\n  return false;\n}",
          "trigger_type": "url",
          "type": "before_send",
        },
        {
          "action": {
            "retry": true
          },
          "action_type": "retry",
          "status": "403",
          "trigger_type": "status",
          "url": "xxx.com/test.php"
        }
      ],
      "seed": "x_session_",
      "session": true,
      "session_termination": true,
      "ssl": true,
      "zone": "zone4"
    }
  ]
}
```

**Comment by falconz** [comment]
I get the same issue

**Comment by khtq** [comment]
The problem is likely occurred only when I enable SSL log

**Comment by khtq** [comment]
More detail error within ubuntu. Probably internal nodejs un-catch exception 
```
(node:19254) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit
2019-04-04 10:26:48.843 ERR: 24002 Hostname/IP does not match certificate's altnames: Host: idsync.rlcdn.com. is not in the cert's altnames: DNS:*.mediaforge.com, DNS:mediaforge.com
2019-04-04 10:26:48.900 ERR: 24002 Exceeded maxRedirects. Probably stuck in a redirect loop https://cm.g.doubleclick.net/pixel?google_nid=TheTradeDesk&google_push&ttd_tdid=80e6cb1c-05bb-4a94-b2a8-95a43000b098
2019-04-04 10:26:48.902 ERR: 24002 Invalid response {"child":{"child_guess":[],"free":true,"then_waiting":[],"info":{},"parent_type":"spawn","tm_completed":1554373608901,"tm_create":1554373607123,"cancelable":true,"_name":"send_bypass_req","name":"send_bypass_req","child":[],"running":false,"use_retval":true,"at_return":true,"error":{},"_finally":3,"states":[{},{"label":"loop","try_catch":true},{},{"finally":true,"sig":true}],"cur_state":4,"generator":{}},"remote_address":"127.0.0.1:45092, 19254/node","uuid":"68fdea20-465e-4072-9348-fe4200c4fdbc"}
2019-04-04 10:26:56.314 CRIT: uncaughtException, error = Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
2019-04-04 10:26:57.658 ERR: Shutdown, reason is uncaughtException, error = Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27): Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
2019-04-04 10:27:00.030 CRIT: uncaughtException, error = Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
2019-04-04 10:27:00.658 CRIT: Forcing exit after 3 sec
```

**Comment by fudali** [comment]
Hi! Thanks for reporting. Are you able to provide me with more information on how to reproduce this issue? Have you found any specific scenario in which it happens? Maybe some specific URL that you send requests to?

**Comment by khtq** [comment]
You can use [this script](https://gist.github.com/khtq/31759fec6a8cb3d6c612dd8ec91ddb62) to reproduce the error. It take a few time to take the LPM crash.

**Comment by khtq** [comment]
@fudali Did you successfully reproduce the error?

**Comment by khtq** [comment]
The connection problem. For anyone have the same problem, check if you are using wifi connection :)
