### ISSUE TITLE
Kubernetes - issue while running with custom config

### ISSUE THREAD

**Issue by botzill** [luminati-io/luminati-proxy#183]
I have the following issues when I try to install it on kubernetes with a custom volume. 

```
2019-04-04 14:11:57.735 ERR: 22999 start error Error: EBUSY: resource busy or locked, rename '/usr/src/config.json' -> '/usr/src/config.json.backup'
    at Object.renameSync (fs.js:591:3)
    at Manager.E.save_config (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/lib/manager.js:647:12)
    at Manager.E.config_check (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/lib/manager.js:1704:10)
    at Etask.mgr_start [as generator_ctor] (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/lib/manager.js:2846:15)
    at mgr_start.next (<anonymous>)
    at Etask.try_catch$loop (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/util/etask.js:1459:54)
    at Etask.E._run (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/util/etask.js:436:41)
    at Etask.E._got_retval (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/util/etask.js:662:14)
    at /usr/local/lib/node_modules/@luminati-io/luminati-proxy/util/etask.js:359:23
    at Etask.E._complete (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/util/etask.js:305:34)
```

Any idea why we have this?

Thx!

**Comment by fudali** [comment]
LPM tries to rename a file ` '/usr/src/config.json' -> '/usr/src/config.json.backup'`. Make sure the process has permissions to do so

**Comment by botzill** [comment]
OK, thx, fixed the issue.
