### ISSUE TITLE
TypeError: Cannot read property 'sessions' of undefined

### ISSUE THREAD

**Issue by neuromantik33** [luminati-io/luminati-proxy#189]
I'm getting an error in the log and I'm not if it is critical or not (since it is in a keep alive handler for sessions)

```
Running proxy configurations...
==================================================
=                                                =
=      Local proxy manager client is running     =
=                                                =
=               Open admin browser:              =
=                                                =
=             http://127.0.0.1:22999             =
=                                                =
=                                                =
=    Do not close the process while using the    =
=    Proxy Manager                               =
=                                                =
==================================================
2019-04-24 12:11:51.696 ERR: 24000 TypeError: Cannot read property 'sessions' of undefined
    at Etask.keep_alive_handler [as generator_ctor] (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/lib/session.js:345:37)
    at keep_alive_handler.next (<anonymous>)
    at Etask.try_catch$loop (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/util/etask.js:1459:54)
    at Etask.E._run (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/util/etask.js:436:41)
    at Etask.E._got_retval (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/util/etask.js:662:14)
    at /usr/local/lib/node_modules/@luminati-io/luminati-proxy/util/etask.js:359:23
    at Etask.E._complete (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/util/etask.js:305:34)
    at Etask.E._next (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/util/etask.js:339:10)
    at Etask.E._run (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/util/etask.js:469:18)
    at Etask.E._next_run (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/util/etask.js:346:10)
```

I can reproduce the conditions but looking at the code, it is confusing how an array could have a property `sessions` (typo perhaps?)
```javascript
function*keep_alive_handler(_this, session){
    if ((!session.pool_keys || !session.pool_keys.size)
        && _this.is_session_expired(session) || _this.lum.stopped)
    {
        return;
    }
    _this.log.info('Keep alive %s:%s', session.host, session.session);
    const res = yield _this.info_request(session, 'SESSION KEEP ALIVE');
    const proxy_err = _this.lum._check_proxy_response(session.host, res,
        {from: 'keep alive', error: res.err});
    const info = res.info;
    let err;
    const curr_ips = _this.sessions.sessions.map(s=>s.info && s.info.ip);
    const this_ip = session.info && session.info.ip;
...
```

Thanks for any assistance

**Comment by fudali** [comment]
Thanks for reporting. Can you also include your configuration file `.luminati.json` ? Please remember to get rid of your credentials and any sensitive information first

**Comment by neuromantik33** [comment]
Thanks for the quick response! :) Here is my `/root/luminati_proxy_manager/.luminati.json` currently running within the docker container

```json
{
  "_defaults": {
    "customer": "*REDACTED*",
    "password": "*REDACTED*",
    "version": "1.131.652",
    "whitelist_ips": [
      "*REDACTED*"
    ]
  },
  "proxies": [
    {
      "country": "*REDACTED*",
      "dns": "remote",
      "keep_alive": true,
      "last_preset_applied": "sticky_ip",
      "max_requests": 0,
      "pool_size": 0,
      "port": 24000,
      "proxy": "*REDACTED*",
      "session": false,
      "ssl": true,
      "sticky_ip": true
    }
  ]
}
```

**Comment by fudali** [comment]
Can you give me more details? Why did you have to remove `proxy` option from the config file? I haven't been able to reproduce the issue so far. Also please try with the newest version of LPM

**Comment by neuromantik33** [comment]
I just removed the `proxy` because it identified which super proxy I was using, no real reason I guess. It is `servercountry-gb.zproxy.lum-superproxy.io`.
I'll try with the newest version of LPM and get back to you.

**Comment by neuromantik33** [comment]
Same error
```
2019-04-24 14:32:15.064 NOTICE: .bashrc not found! alias for whitelisting failed

Loaded config /root/luminati_proxy_manager/.luminati.json
Running proxy configurations...
==================================================
=                                                =
=      Local proxy manager client is running     =
=                                                =
=               Open admin browser:              =
=                                                =
=             http://127.0.0.1:22999             =
=                                                =
=                                                =
=    Do not close the process while using the    =
=    Proxy Manager                               =
=                                                =
==================================================
2019-04-24 14:35:44.979 ERR: 24000 TypeError: Cannot read property 'sessions' of undefined
    at Etask.keep_alive_handler [as generator_ctor] (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/lib/session.js:345:37)
    at keep_alive_handler.next (<anonymous>)
    at Etask.try_catch$loop (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/util/etask.js:1459:54)
    at Etask.E._run (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/util/etask.js:436:41)
    at Etask.E._got_retval (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/util/etask.js:662:14)
    at /usr/local/lib/node_modules/@luminati-io/luminati-proxy/util/etask.js:359:23
    at Etask.E._complete (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/util/etask.js:305:34)
    at Etask.E._next (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/util/etask.js:339:10)
    at Etask.E._run (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/util/etask.js:469:18)
    at Etask.E._next_run (/usr/local/lib/node_modules/@luminati-io/luminati-proxy/util/etask.js:346:10)
```
You need to wait a while for it though, just tailing the logs (I'm running the proxymgr as a docker image) should show it. Here is my configuration file:

```json
{
  "_defaults": {
    "customer": "*REDACTED*",
    "password": "*REDACTED*",
    "token": "",
    "version": "1.132.341",
    "whitelist_ips": [
      "*REDACTED*"
    ]
  },
  "proxies": [
    {
      "country": "*REDACTED*",
      "dns": "remote",
      "keep_alive": true,
      "last_preset_applied": "sticky_ip",
      "max_requests": 0,
      "pool_size": 0,
      "port": 24000,
      "proxy": "servercountry-gb.zproxy.lum-superproxy.io",
      "session": false,
      "ssl": true,
      "sticky_ip": true
    }
  ]
}
```

**Comment by fudali** [comment]
It's been fixed in the newest version
