### ISSUE TITLE
Server keeps crashing within the 5-10 minute mark 

### ISSUE THREAD

**Issue by vicngtor** [luminati-io/luminati-proxy#30]
I keep seeing this message. Any ideas what's causing this? 

```
vng:/Users/vng/Desktop () $ luminati --resolve resolve.txt
admin is available at http://127.0.0.1:22999
2016-12-24T02:02:18.232Z - 24444 - error: CONNECT client-s.gateway.messenger.live.com:443 - 403
2016-12-24T02:02:19.373Z - 24444 - error: CONNECT client-s.gateway.messenger.live.com:443 - 403
2016-12-24T02:02:21.483Z - 24444 - error: CONNECT client-s.gateway.messenger.live.com:443 - 403
2016-12-24T02:02:22.883Z - 24444 - error: CONNECT client-s.gateway.messenger.live.com:443 - 403
2016-12-24T02:03:09.976Z - 24444 - error: CONNECT client-s.gateway.messenger.live.com:443 - 403
2016-12-24T02:03:11.258Z - 24444 - error: CONNECT client-s.gateway.messenger.live.com:443 - 403
2016-12-24T02:03:16.688Z - 24444 - error: CONNECT client-s.gateway.messenger.live.com:443 - 403
2016-12-24T02:03:17.910Z - 24444 - error: CONNECT client-s.gateway.messenger.live.com:443 - 403
2016-12-24T02:03:45.840Z - 24444 - error: HTTP error Error: listen EADDRINUSE 0.0.0.0:24444
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1257:14)
    at listen (net.js:1293:10)
    at net.js:1403:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
There's already an application which runs on 0.0.0.0:24444
```

It happens about 5-10 minutes into using the server

**Comment by lee-elenbaas** [comment]
This error state that the port 24444 was in use when the program tried to start listen to it
two possible reasons:
- you have another app on your computer that uses that port (use net stat or something similar to find out what it is)
- you by mistake have configured that port more then once in the config file (open the config file using a test editor, to fix that issue, or delete it)

**Comment by lee-elenbaas** [comment]
I am closing this for lack of activity - if you can shed more info - please reopen it

**Comment by Stiveknx** [comment]
The issue is still happening to me.

If I just open another port, or if I click in "clone zone", the script shutdown, with EADDRINUSE error.
```
2018-08-31 00:07:00.586 ERR: socks:24004-24004 server error {"errno":"EADDRINUSE","code":"EADDRINUSE","syscall":"listen","address":"0.0.0.0","port":24004}
2018-08-31 00:07:00.587 CRIT: uncaughtException, error = Error: listen EADDRINUSE 0.0.0.0:24004
    at Object._errnoException (util.js:999:13)
    at _exceptionWithHostPort (util.js:1020:20)
    at Server.setupListenHandle [as _listen2] (net.js:1379:14)
    at listenInCluster (net.js:1420:12)
    at doListen (net.js:1535:7)
    at process._tickCallback (internal/process/next_tick.js:152:19)
2018-08-31 00:07:00.614 ERR: Shutdown, reason is uncaughtException, error = Error: listen EADDRINUSE 0.0.0.0:24004
    at Object._errnoException (util.js:999:13)
    at _exceptionWithHostPort (util.js:1020:20)
    at Server.setupListenHandle [as _listen2] (net.js:1379:14)
    at listenInCluster (net.js:1420:12)
    at doListen (net.js:1535:7)
    at process._tickCallback (internal/process/next_tick.js:152:19): Error: listen EADDRINUSE 0.0.0.0:24004
    at Object._errnoException (util.js:999:13)
    at _exceptionWithHostPort (util.js:1020:20)
    at Server.setupListenHandle [as _listen2] (net.js:1379:14)
    at listenInCluster (net.js:1420:12)
    at doListen (net.js:1535:7)
    at process._tickCallback (internal/process/next_tick.js:152:19)
2018-08-31 00:07:01.095 NOTICE: 22999 Manager stopped {"reason":"uncaughtException, error = Error: listen EADDRINUSE 0.0.0.0:24004\n    at Object._errnoException (util.js:999:13)\n    at _exceptionWithHostPort (util.js:1020:20)\n    at Server.setupListenHandle [as _listen2] (net.js:1379:14)\n    at listenInCluster (net.js:1420:12)\n    at doListen (net.js:1535:7)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","force":true}
```

I don't use another program on that port

```
# netstat -plnt
Conexões Internet Ativas (sem os servidores)
Proto Recv-Q Send-Q Endereço Local          Endereço Remoto         Estado      PID/Program name    
tcp        0      0 51.255.92.89:8080       0.0.0.0:*               OUÇA       6873/node           
tcp        0      0 0.0.0.0:80              0.0.0.0:*               OUÇA       1522/nginx: master  
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               OUÇA       1522/nginx: master  
tcp        0      0 0.0.0.0:22              0.0.0.0:*               OUÇA       1188/sshd           
tcp        0      0 127.0.0.1:9000          0.0.0.0:*               OUÇA       1152/php-fpm: pool  
tcp        0      0 127.0.0.1:9001          0.0.0.0:*               OUÇA       5959/php-fpm: maste 
tcp6       0      0 :::21                   :::*                    OUÇA       1228/vsftpd         
tcp6       0      0 :::22                   :::*                    OUÇA       1188/sshd           
```

**Comment by Stiveknx** [comment]
The issue is still happening to me.

If I just open another port, or if I click in "Duplicate Proxy Port", the script shutdown, with EADDRINUSE error.
```
2018-08-31 00:07:00.586 ERR: socks:24004-24004 server error {"errno":"EADDRINUSE","code":"EADDRINUSE","syscall":"listen","address":"0.0.0.0","port":24004}
2018-08-31 00:07:00.587 CRIT: uncaughtException, error = Error: listen EADDRINUSE 0.0.0.0:24004
    at Object._errnoException (util.js:999:13)
    at _exceptionWithHostPort (util.js:1020:20)
    at Server.setupListenHandle [as _listen2] (net.js:1379:14)
    at listenInCluster (net.js:1420:12)
    at doListen (net.js:1535:7)
    at process._tickCallback (internal/process/next_tick.js:152:19)
2018-08-31 00:07:00.614 ERR: Shutdown, reason is uncaughtException, error = Error: listen EADDRINUSE 0.0.0.0:24004
    at Object._errnoException (util.js:999:13)
    at _exceptionWithHostPort (util.js:1020:20)
    at Server.setupListenHandle [as _listen2] (net.js:1379:14)
    at listenInCluster (net.js:1420:12)
    at doListen (net.js:1535:7)
    at process._tickCallback (internal/process/next_tick.js:152:19): Error: listen EADDRINUSE 0.0.0.0:24004
    at Object._errnoException (util.js:999:13)
    at _exceptionWithHostPort (util.js:1020:20)
    at Server.setupListenHandle [as _listen2] (net.js:1379:14)
    at listenInCluster (net.js:1420:12)
    at doListen (net.js:1535:7)
    at process._tickCallback (internal/process/next_tick.js:152:19)
2018-08-31 00:07:01.095 NOTICE: 22999 Manager stopped {"reason":"uncaughtException, error = Error: listen EADDRINUSE 0.0.0.0:24004\n    at Object._errnoException (util.js:999:13)\n    at _exceptionWithHostPort (util.js:1020:20)\n    at Server.setupListenHandle [as _listen2] (net.js:1379:14)\n    at listenInCluster (net.js:1420:12)\n    at doListen (net.js:1535:7)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","force":true}
```

I don't use another program on that port

```
# netstat -plnt
Conexões Internet Ativas (sem os servidores)
Proto Recv-Q Send-Q Endereço Local          Endereço Remoto         Estado      PID/Program name    
tcp        0      0 *.*.*.*:8080       0.0.0.0:*               OUÇA       6873/node           
tcp        0      0 0.0.0.0:80              0.0.0.0:*               OUÇA       1522/nginx: master  
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               OUÇA       1522/nginx: master  
tcp        0      0 0.0.0.0:22              0.0.0.0:*               OUÇA       1188/sshd           
tcp        0      0 127.0.0.1:9000          0.0.0.0:*               OUÇA       1152/php-fpm: pool  
tcp        0      0 127.0.0.1:9001          0.0.0.0:*               OUÇA       5959/php-fpm: maste 
tcp6       0      0 :::21                   :::*                    OUÇA       1228/vsftpd         
tcp6       0      0 :::22                   :::*                    OUÇA       1188/sshd           
```
