### ISSUE TITLE
Failed to resolve any proxies

### ISSUE THREAD

**Issue by boxbeatsy** [luminati-io/luminati-proxy#35]
I'm on luminati v0.9.63

When I try to run the following command, I get an error.

**Command:** luminati --no_dropin --keep_alive --zone="city" --city="any_city_eg_san_diego" --state="any_state_eg_ca" --country="us" --customer="my_customer_un" --password="my_password" --www=23001 24001.json

**Error:** 2017-02-21T23:06:27.088Z - 24032 - error: Failed to resolve any proxies

The contents of my json config are:  {"port": "24001", "country": "us", "sticky_ip": true, "max_requests": 0}

This keeps happening to me over and over.  I've found a solution, but it requires manual intervention, and every time I fix the problem, it happens again in a few days.

The work around I've found is:
1) running the plain command "luminati"
2) logging in with my account credentials at 127.0.0.1:22999
3) removing the "proxies" key from the dictionary in ~/.luminati.json (if i don't do this, then my actual command will throw a 24000 port error)

Could I get help identifying the root cause of this error, so I don't have to manually reset my configs every time this happens? Thank you!

**Comment by boxbeatsy** [comment]
For additional context, when running with --log="silly", I get the following error:

2017-02-21T23:17:22.376Z - 24032 - debug: Failed to resolve zproxy.luminati.io (customer-lum-customer-username-zone-zonename-session-1487719042284.zproxy.luminati.io): Error: queryA ENOTFOUND customer-lum-customer-username-zone-zonename-session-1487719042284.zproxy.luminati.io
2017-02-21T23:17:22.377Z - 24032 - silly: Error: queryA ENOTFOUND customer-lum-customer-username-zone-zonename-session-1487719042284.zproxy.luminati.io
    at errnoException (dns.js:28:10)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:219:19) root
 \_ RUNNING resolve_proxy.1 30.086s

**Comment by jaspax** [comment]
Hi, boxbeatsy:

The ENOTFOUND error means that your session has expired. That in turn suggests that the password which is being stored in ~/.luminati.json is no longer correct (since we don't store your actual plaintext password, but rather a session key). That's why logging in again with the UI causes things to work: you're refreshing your password. The --password that you give on the command line doesn't actually work in version 0.9.63.

The fact that you have to remove the "proxies" section from .luminati.json is similar: that's overriding the things that's present on the command line.

We should be releasing 0.9.70 later today to address both of these issues.

**Comment by ovidiuD** [comment]
closing due to no activity for more than 2 weeks
