### ISSUE TITLE
Installing ProxyManager on MacOS (10.12.6)

### ISSUE THREAD

**Issue by joergrech** [luminati-io/luminati-proxy#63]
when running the following command as a **normal user** (not root):
````sudo rm -rf /usr/local/lib/node_modules/luminati-proxy/node_modules && sudo npm install -g luminati-io/luminati-proxy````

I get: 

```
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone -q git://github.com/lee-elenbaas/socksv5.git /Users/jorgrech/.npm/_cacache/tmp/git-clone-a1abbc5f
npm ERR! /Users/jorgrech/.npm/_cacache/tmp/git-clone-a1abbc5f/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jorgrech/.npm/_logs/2017-08-27T13_08_37_387Z-debug.log
````

when running as **root** I get:

````
npm WARN deprecated tough-cookie@0.12.1: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
/usr/local/bin/luminati -> /usr/local/lib/node_modules/luminati-proxy/bin/luminati.js
/usr/local/bin/luminati-proxy -> /usr/local/lib/node_modules/luminati-proxy/bin/luminati.js

> fsevents@1.1.2 install /usr/local/lib/node_modules/luminati-proxy/node_modules/fsevents
> node install

[fsevents] Success: "/usr/local/lib/node_modules/luminati-proxy/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> phantomjs-prebuilt@2.1.15 install /usr/local/lib/node_modules/luminati-proxy/node_modules/phantomjs-prebuilt
> node install.js

Considering PhantomJS found at /usr/local/bin/phantomjs
Found PhantomJS at /usr/local/bin/phantomjs ...verifying
Writing location.js file
Error checking path, continuing { Error: EACCES: permission denied, open '/usr/local/lib/node_modules/luminati-proxy/node_modules/phantomjs-prebuilt/lib/location.js'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.writeFileSync (fs.js:1347:33)
    at writeLocationFile (/usr/local/lib/node_modules/luminati-proxy/node_modules/phantomjs-prebuilt/lib/util.js:84:6)
    at Promise._successFn (/usr/local/lib/node_modules/luminati-proxy/node_modules/phantomjs-prebuilt/install.js:375:11)
    at nextTickCallback (/usr/local/lib/node_modules/luminati-proxy/node_modules/kew/kew.js:47:28)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/usr/local/lib/node_modules/luminati-proxy/node_modules/phantomjs-prebuilt/lib/location.js' }
Download already available at /tmp/phantomjs/phantomjs-2.1.1-macosx.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing /usr/local/lib/node_modules/luminati-proxy/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1503839421346/phantomjs-2.1.1-macosx -> /usr/local/lib/node_modules/luminati-proxy/node_modules/phantomjs-prebuilt/lib/phantom
Phantom installation failed { Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1503839421346/phantomjs-2.1.1-macosx' -> '/usr/local/lib/node_modules/luminati-proxy/node_modules/phantomjs-prebuilt/lib/phantom'
    at Error (native)
  errno: -13,
  code: 'EACCES',
  syscall: 'link',
  path: '/tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1503839421346/phantomjs-2.1.1-macosx',
  dest: '/usr/local/lib/node_modules/luminati-proxy/node_modules/phantomjs-prebuilt/lib/phantom' } Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1503839421346/phantomjs-2.1.1-macosx' -> '/usr/local/lib/node_modules/luminati-proxy/node_modules/phantomjs-prebuilt/lib/phantom'
    at Error (native)

> sqlite3@3.1.8 install /usr/local/lib/node_modules/luminati-proxy/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/local/bin/node',
node-pre-gyp verb cli   '/usr/local/lib/node_modules/luminati-proxy/node_modules/sqlite3/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.31
node-pre-gyp info using node@6.11.0 | darwin | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/usr/local/lib/node_modules/luminati-proxy/node_modules/sqlite3/lib/binding/node-v48-darwin-x64/node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v48-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v48-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.8 and node@6.11.0 (node-v48 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http EACCES: permission denied, mkdir '/usr/local/lib/node_modules/luminati-proxy/node_modules/sqlite3/lib/binding' 
node-pre-gyp verb command build [ 'rebuild' ]
node-pre-gyp http 200 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v48-darwin-x64.tar.gz
gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/jorgrech/.node-gyp/6.11.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/luminati-proxy/node_modules/sqlite3/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/local/lib/node_modules/luminati-proxy/node_modules/sqlite3/.node-gyp/6.11.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/luminati-proxy/node_modules/sqlite3/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/local/lib/node_modules/luminati-proxy/node_modules/sqlite3/.node-gyp/6.11.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/luminati-proxy/node_modules/sqlite3/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/local/lib/node_modules/luminati-proxy/node_modules/sqlite3/.node-gyp/6.11.0"

... (it never ends)
````

btw: The directory "/usr/local/lib/node_modules/luminati-proxy/node_modules/sqlite3/" exists but "/.node-gyp/6.11.0" does not.

**Comment by mrodessit** [comment]
Same issue.

**Comment by Eloverflow** [comment]
Maybe following the logic of my move in the following comment (Worked for me):
https://github.com/luminati-io/luminati-proxy/issues/62#issuecomment-346979139

**Comment by sk91** [comment]
Hi, if it’s still an issue, try using our install script. It should fix it automatically.
‘wget -qO- https://luminati.io/static/lpm/luminati-proxy-latest-setup.sh | bash’
