### ISSUE TITLE
Luminate not run windows

### ISSUE THREAD

**Issue by dacopan** [luminati-io/luminati-proxy#81]
Open admin browser: http://undefined:undefined
(node:7080) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 1
(node:7080) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2018-02-06 15:30:24.819 WARN: 22999 API error: GET /api/www_lpm Error: connect EAFNOSUPPORT 184.73.155.216:443 - Local (undefined:undefined)
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at internalConnect (net.js:894:16)
    at emitLookup (net.js:1020:7)
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:10)
2018-02-06 15:30:24.826 ERR: 22999 Error: connect EAFNOSUPPORT 184.73.155.216:443 - Local (undefined:undefined)
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at internalConnect (net.js:894:16)
    at emitLookup (net.js:1020:7)
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:10)

**Comment by sk91** [comment]
Hi @dacopan, 

please answer the following questions:
- How did you install luminati? Via command line or windows setup file?
- How do you start luminati? Which parameters do you use?

Max

**Comment by sk91** [comment]
closing, no activity
